[package]
name = "rzbackup"
version = "2.0.9"
description = "RZBackup"
authors = [ "James Pharaoh <james@pharaoh.uk>" ]
license = "Apache-2.0"
homepage = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/wbs-backup"
repository = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/wbs-backup"
readme = "README.md"
build = "src/build.rs"

exclude = [
	"src/zbackup/metadata.rs",
	"target/**/*",
	"work/**/*",
]

[[bin]]
name = "rzbackup-client"
path = "src/bin/client.rs"

[[bin]]
name = "rzbackup-decrypt"
path = "src/bin/decrypt.rs"

[[bin]]
name = "rzbackup-server"
path = "src/bin/server.rs"

[[bin]]
name = "rzbackup-restore"
path = "src/bin/restore.rs"

[dependencies]
clap = "2.13"
futures = "0.1"
futures-cpupool = "0.1"
libc = "0.2"
lru-cache = "0.0"
minilzo = "0.1"
num_cpus = "1.1"
protobuf = "1.0"
rust-crypto = "0.2"
rustc-serialize = "0.3"

# ex: noet ts=4 filetype=cargo
