[package]

	name = "rzbackup"
	version = "3.1.1"
	description = "RZBackup"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	license = "Apache-2.0"
	homepage = "http://rzbackup.com"
	repository = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/rzbackup"
	readme = "README.md"

	build = "src/build.rs"

	exclude = [
		"src/zbackup/metadata.rs",
		"target/**/*",
		"work/**/*",
	]

[dependencies]

	adler32 = "0.3"
	byteorder = "0.5"
	clap = "2.13"
	futures = "0.1"
	futures-cpupool = "0.1"
	libc = "0.2"
	lru-cache = "0.0"
	minilzo = "0.1"
	num_cpus = "1.1"
	output = "0.4"
	protobuf = "1.0"
	rand = "0.3"
	rust-crypto = "0.2"
	rustc-serialize = "0.3"

[[bin]]

	name = "rzbackup-client"
	path = "src/bin/client.rs"

[[bin]]

	name = "rzbackup-convert"
	path = "src/bin/convert.rs"

[[bin]]

	name = "rzbackup-decrypt"
	path = "src/bin/decrypt.rs"

[[bin]]

	name = "rzbackup-restore"
	path = "src/bin/restore.rs"

[[bin]]

	name = "rzbackup-server"
	path = "src/bin/server.rs"

# ex: noet ts=4 filetype=cargo
