[package]
name = "rzbackup"
description = "RZBackup"
version = "0.1.0"
authors = [ "James Pharaoh <james@pharaoh.uk>" ]
license = "Apache-2.0"
homepage = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/wbs-backup"
repository = "https://gitlab.wellbehavedsoftware.com/well-behaved-software/wbs-backup"
readme = "README.md"

include = [
	"etc/**/*",
	"src/**/*",
	"Cargo.toml",
]

[[bin]]
name = "rzbackup-client"
path = "src/bin/client.rs"

[[bin]]
name = "rzbackup-decrypt"
path = "src/bin/decrypt.rs"

[[bin]]
name = "rzbackup-server"
path = "src/bin/server.rs"

[[bin]]
name = "rzbackup-restore"
path = "src/bin/restore.rs"

[dependencies]
libc = '0.2'
lru-cache = '0.0'
protobuf = '1.0'
rust-crypto = '0.2'
rustc-serialize = '0.3'
